const A = `¿Tendrías relaciones con alguien de este grupo?`
const B = `¿Has tenido relaciones con alguien de este grupo? `
const C = `¿Quién es la persona más sexy aquí? `
const D = `¿Alguna vez has pensado en engañar a una pareja tuya? `
const E = `¿Por qué crees que te pusieron tu nombre?`
const F = ` ¿Quién de las personas de este grupo tiene el cuerpo más bonito?`
const G = `¿Has tenido relaciones con un desconocido/a? `
const H = `¿Qué querías ser de adulto cuando eras niño?`
const I = ` ¿Alguna vez te han sorprendido teniendo sexo?`
const J = `¿Cómo intentarías seducir a alguien que te gusta?`
const K = `¿Has quedado con alguien que has conocido en Internet? `
const L = `¿Cuál ha sido el sueño más extraño que has tenido?`
const M = `De este grupo, ¿a quién le robarías un beso? `
const N = `¿Alguna vez te has olvidado del nombre de la persona con la que te has acostado?`
const Ñ = `¿Qué harías si un/a desconocido/a te besara en plena calle?`
const O = `¿Cuál es el mejor lugar para hacerlo?`
const P = `¿Qué es lo más loco que has hecho por amor?`
const Q = `Si te tuvieras que poner un nombre a ti mismo, ¿cuál sería?`
const R = `¿Has tenido algún sueño erótico con alguien de aquí?`
const S = `¿Alguna vez has hecho un trío?`
const T = `¿Qué es lo más vergonzoso que te han pillado haciendo?`
const U = `¿Qué es algo que nunca te has atrevido a pedir?`
const V = `¿Alguna vez te han pillado mintiendo?`
const W = `¿Crees que a veces es mejor no decir la verdad?`
const X = `Si pudieras ir a cenar con un famoso o una famosa, ¿con quién irías?`
const Y = `¿Qué es lo que te pone más nervioso?`
const Z = `¿Hablas contigo en voz alta?`
const AA = `¿Quién te cae mejor en este grupo?`
const BB = `¿Quién te cae peor en este grupo?`
const CC = `¿Recuerdas dónde fue tu primer beso y con quién? Cuentanos...`
const DD = `¿Has tenido una relación secreta con alguna de las personas del grupo?`
const EE = `¿Quién del grupo crees que es más probable que tenga hijos antes?`
const FF = `¿Quién del grupo crees que es más probable que vuelva con su ex?`
const GG = `¿Te has operado alguna vez?`
const HH = `¿Alguna vez te ha gustado algún/a profesor/a?`
const II = `¿Cuál es tu postura sexual favorita?`
const JJ = `¿Alguna vez te has enamorado de quien no deberías?`
const KK = `¿A quién te gustaría besar en este grupo?`
const LL = `¿Qué es lo que *te gustaría* que la gente supiera de ti?`
const MM = `¿Cuál es el mejor consejo que te han dado?`
const NN = `¿Qué has comprado que haya sido el mayor despilfarro de dinero?`
const OO = `¿Cómo te sentirías si pillas a tu pareja dándose autoplacer?`
const PP = `¿Qué es lo más loco que has hecho por un chico o una chica?`
const QQ = `¿Te gusta tu trabajo? SI, NO ¿Por qué?`
const RR = `¿Has sentido atracción por algún amigo/a de tu pareja actual o anteriores? SI, NO ¿Qué hiciste?`
const SS = `¿Te han pillado dándote autoplacer?`
const TT = `¿Cuál fue el motivo de tu última ruptura de pareja?`
const UU = `¿Sientes o has sentido atracción física por algún familiar lejano?`
const VV = `¿Qué es lo más loco que has hecho para intentar gustar a alguien?`
const WW = `¿Tienes algún primo o prima con el que no te importaría tener una relación?`
const XX = `¿Qué es lo más ridículo que te ha pasado intentando seducir a alguien?`
const YY = `¿Cuál es la técnica de seducción que más usas al flirtear?`
const ZZ = `¿Cuál es la caída más graciosa que has sufrido estando delante de los demás?`


module.exports = {
    A, B, C, D, E, F, G, H, I, J, K, L, M, N, Ñ, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, BB, CC, DD, EE, FF, GG, HH, II, JJ, KK, LL, MM, NN, OO, PP, QQ, RR, SS, TT, UU, VV, WW, XX, YY, ZZ
}